name: 'Run smoke tests'
description: 'Runs smoke tests'
inputs:
  python-version:
    required: true
    description: >-
      Python version to use. Must be in the form of "3.xx".
runs:
  using: "composite"
  steps:
    - name: "Install packages"
      shell: bash
      run: |
        cat /etc/os-release
        sudo dnf install -y gcc gcc-c++ make git-core python${{ inputs.python-version }} python${{ inputs.python-version }}-devel

    - name: "Verify cuda environment is setup"
      shell: bash
      run: |
        export CUDA_HOME="/usr/local/cuda"
        export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${CUDA_HOME}/lib64:${CUDA_HOME}/extras/CUPTI/lib64"
        export PATH="${PATH}:${CUDA_HOME}/bin"
        nvidia-smi

    # installs in $GITHUB_WORKSPACE/venv.
    # only has to install Tox because Tox will do the other virtual environment management.
    - name: "Setup Python virtual environment"
      shell: bash
      run: |
        python${{ inputs.python-version }} -m venv --upgrade-deps venv
        . venv/bin/activate
        pip install tox -c constraints-dev.txt

    - name: "Show disk utilization BEFORE tests"
      shell: bash
      if: always()
      run: |
        df -h

    - name: "Run smoke tests with Tox and Pytest"
      shell: bash
      run: |
        source venv/bin/activate
        tox -e py3-smoke

    - name: "Show disk utilization AFTER tests"
      shell: bash
      if: always()
      run: |
        df -h
